# DataSource Config
spring:
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:sql/schema.sql
    data: classpath:sql/data.sql
    url: jdbc:h2:mem:test
    username: sa
    password: sa
  h2:
    console:
      enabled: true